services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-wordpress}
      MYSQL_USER: ${DB_USER:-wp_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-wp_password}
    volumes:
      - db_data:/var/lib/mysql
    command: --innodb-buffer-pool-size=512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    command: redis-server --appendonly yes
    security_opt:
      - no-new-privileges:true

  wordpress:
    build: wordpress/.
    depends_on:
      - db
      - redis
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${DB_USER:-wp_user}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD:-wp_password}
      WORDPRESS_DB_NAME: ${DB_NAME:-wordpress}
      PHP_OPCACHE_ENABLE: '1'
      PHP_OPCACHE_MEMORY_CONSUMPTION: '128'
      PHP_OPCACHE_INTERNED_STRINGS_BUFFER: '8'
      PHP_OPCACHE_MAX_ACCELERATED_FILES: '4000'
      WP_REDIS_HOST: 'redis'
      WP_REDIS_PORT: 6379
    volumes:
      - wp_data:/var/www/html
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    healthcheck:
      test: [ "CMD-SHELL", "pgrep php-fpm || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s


  varnish:
    image: varnish:7-alpine
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
    depends_on:
      - nginx
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl:ro
    command: ['varnishd', '-F', '-f', '/etc/varnish/default.vcl', '-a', '0.0.0.0:80']
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/", "-o", "/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - wordpress
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - wp_data:/var/www/html
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    security_opt:
      - no-new-privileges:true

volumes:
  db_data:
  redis_data:
  wp_data:

